spring:
  application:
    name: testapp
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:
  sql:
    init:
      mode: always
  messages:
    basename: messages
    encoding: UTF-8
